ALTER TABLE "business" ALTER COLUMN "country" SET DEFAULT 'NPL';--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_content" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_content" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_analytics" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_analytics" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_ads" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_ads" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_read_dms" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_read_dms" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_reply_dms" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_reply_dms" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_read_comments" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_read_comments" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_reply_comments" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_reply_comments" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_leads" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_leads" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_leads" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_leads" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_bookings" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_bookings" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_bookings" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_bookings" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_inventory" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_inventory" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_inventory" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_inventory" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_orders" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_view_orders" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_settings" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_settings" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_members" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_members" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_billing" SET DEFAULT false;--> statement-breakpoint
ALTER TABLE "business_members" ALTER COLUMN "can_manage_billing" SET NOT NULL;